name: cross_platform_test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '**.md'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '.gitignore'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # ワークフローの可視化
      - uses: Kesin11/actions-timeline@v2
      # チェックアウト
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      # # imageをpullする
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/tomo1227/blogs
          cacheFrom: ghcr.io/tomo1227/blogs
          push: always
          runCmd: docker-compose ps
      # devcontainerのテスト
      # - name: Build and run Dev Container task
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     imageName: ghcr.io/tomo1227/blogs
      #     runCmd: |
      #       python -V
      #       docker-compose ps
      
